# The network-interface the webserver will bind to (0.0.0.0 for all interfaces, 127.0.0.1 for only local access).
webserver-bindaddress: 0.0.0.0

# The TCP-port the webserver will listen on.
webserver-port: 8124
